[versions]
agp = "8.13.2"
kotlin = "2.3.0"
junit4 = "4.13.2"
kotlinxCoroutinesTest = "1.9.0"
smaliDexlib2 = "3.0.9"
androidxTest = "1.7.0"
robolectric = "4.16"
kotlin-binary-compatibility-validator = "0.18.1"
vibeJs = "0.0.1"

[libraries]
junit4 = { group = "junit", name = "junit", version.ref = "junit4" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinxCoroutinesTest" }
smali-dexlib2 = { module = "com.android.tools.smali:smali-dexlib2", version.ref = "smaliDexlib2" }
androidx-test-core = { module = "androidx.test:core", version.ref = "androidxTest" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
vibe-js = { module = "com.muedsa.js:vibe-js", version.ref = "vibeJs" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-binary-compatibility-validator = { id = "org.jetbrains.kotlinx.binary-compatibility-validator", version.ref = "kotlin-binary-compatibility-validator"}
